### ISSUE TITLE
Question - Beosound emerge

### ISSUE THREAD

**Issue by madmaiike** [giachello/mlgw#23]
Hi there, 

Wondering if I'll be able to group Besound Emerge with other devices (namely arylic wifi amp) to a single group via HA using that extension. 

Thanks

**Comment by giachello** [comment]
No. The Beosound Emerge runs off the Mozart API (separate integration ,look for it on github).
The way media_players work on HA is that you can control them but not share audio streams across different platforms.

**Comment by madmaiike** [comment]
Thanks for the quick response
