### ISSUE TITLE
Not seeing MLGW_telegram events in HA from BLGW when using bluetooth remote

### ISSUE THREAD

**Issue by blackbart321** [giachello/mlgw#25]
Firstly thankyou for this development. It is awesome and use it to control lights in my house from BO remotes. Super cool

I have an odd issue. I have installed a Beosound 35. It can receive LIGHT commands use IR from a Beo4 remote and BT from a BeoOne remote. When I press the LIGHT key on the Beo4 and a command using IR,  I can see the command on the BLGW. I do the same LIGHT command with BeoOne BT remote and the commands are the same on the BLGW. However only the command originating from IR is visible in HA when I monitor the mlgw.MLGW_telegram event bus. No commands come though to mlgw.MLGW_telegram event bus when using the BT remote. 

I can write macros on the BLGW that respond to both IR and BT commands so I know the BLGW is receiving them and I can see both in the logs. They are identical. see example below

From BT

23-08-14 21:35:15 Event fired HAUS/Bedroom/AV renderer/BeoSound 35/Light?Action=Press&Command=CIFFER_9_Digit_9

From IR
23-08-14 21:35:21 Event fired HAUS/Bedroom/AV renderer/BeoSound 35/Light?Action=Press&Command=CIFFER_9_Digit_9

I tried the same with a BO Core thinking it was a limitation of the Beosound 35 but I got the same result.  

Any ideas why the BT originating commands are not going from the BLGW to HA? I was hoping the migrate to BT remotes as they are now obsolete and all the new B&O kit no longer has IR

**Comment by giachello** [comment]
Hi! this is interesting.

I don't have a BLGW, just an older MLGW, so not sure about its configuration. maybe there is a different config for BT vs. IR?

Did you try to look at the ML_telegram stream and see if there is a message there?

I do have a BeoVision Avant and the BT remote on it does in fact transmit the Light commands fine.

I did have to configure the BeoVision to send LIGHT commands to the mlgw.

**Comment by blackbart321** [comment]
thankyou. I looked at the ML_telegram stream as well and could not see anything. It is odd. I have a Beosystem 4 which has the same engine as the Avant and I can see the LIGHT commands. It is just the later products. I did solve it with your beoplay component. It can see LIGHT commands from the newer NL products. which is awesome. It does mean you need a different method for each of the product sets (ie. ML vs NL) but the LIGHT commands can be detected. It is odd

**Comment by giachello** [comment]
Great to hear. Will close this and add it to the known problems.

**Comment by blackbart321** [comment]
Thankyou. It worked for beosystem 4 which is the same as avant.  It did not work for core or beosound 35.  I have a level which does not integrate to BLGW so this never workedThanks again for an awesome pluginCheersOn 19 Aug 2023, at 1:03 am, Giovanni Iachello ***@***.***> wrote:﻿
Great to hear. Will close this and add it to the known problems.
