### ISSUE TITLE
State changes only for Audio product

### ISSUE THREAD

**Issue by oskarax** [giachello/mlgw#8]
Hi, I'm trying to trigger an automation based on what source is being selected. In my case I want to trigger when select source TV is pressed. But it seems that the integration only reports Audio commands like CD, RADIO, AUX. Not Video like TV.

Is that something you could implement?

**Comment by giachello** [comment]
Hi! 
TV sources should work. Can you send me details of your setup and a log of the events that happen when you select the TV source?
Giovanni

**Comment by oskarax** [comment]
HI! I have a Beosystem 3 and a BS9000 connected with master link and of course a mlgw. Im not sure how or what logs you're after but this is when I press the TV button on my beo4 remote and its on the mlgw.ML_telegram event bus. Let me know if there is something else I can provide.

Händelse 7 utlöst 22:24:
{
    "event_type": "mlgw.ML_telegram",
    "data": {
        "from_device": "VIDEO_MASTER",
        "to_device": "ALL_LINK_DEVICES",
        "type": "RESPONSE",
        "src_dest": "NONE",
        "orig_src": "NONE",
        "payload_type": "VIDEO_TRACK_INFO",
        "payload_len": 7,
        "payload": {
            "source": "DTV",
            "sourceID": 31,
            "channel_track": "0xffff",
            "activity": "Playing"
        },
        "timestamp": "2021-07-21T22:23:46.439000",
        "bytes": "83c0011400000094070202ffff1f020094",
        "from_mln": 6
    },
    "origin": "LOCAL",
    "time_fired": "2021-07-21T20:24:13.827779+00:00",
    "context": {
        "id": "e0ca8c981e6a44df9db45c28f8676cc2",
        "parent_id": null,
        "user_id": null
    }
}
Händelse 6 utlöst 22:24:
{
    "event_type": "mlgw.ML_telegram",
    "data": {
        "from_device": "VIDEO_MASTER",
        "to_device": "ALL_LINK_DEVICES",
        "type": "INFO",
        "src_dest": "NONE",
        "orig_src": "NONE",
        "payload_type": "START_VIDEO_DISTRIBUTION",
        "payload_len": 1,
        "payload": {},
        "timestamp": "2021-07-21T22:23:46.416000",
        "bytes": "83c0012c00000007010003",
        "from_mln": 6
    },
    "origin": "LOCAL",
    "time_fired": "2021-07-21T20:24:13.827530+00:00",
    "context": {
        "id": "9814fe258291cd456c92a4265b44f215",
        "parent_id": null,
        "user_id": null
    }
}
Händelse 5 utlöst 22:24:
{
    "event_type": "mlgw.ML_telegram",
    "data": {
        "from_device": "VIDEO_MASTER",
        "to_device": "ALL_LINK_DEVICES",
        "type": "RESPONSE",
        "src_dest": "NONE",
        "orig_src": "NONE",
        "payload_type": "VIDEO_TRACK_INFO",
        "payload_len": 7,
        "payload": {
            "source": "DTV",
            "sourceID": 31,
            "channel_track": "0xffff",
            "activity": "Playing"
        },
        "timestamp": "2021-07-21T22:23:46.239000",
        "bytes": "83c0011400000094070202ffff1f020094",
        "from_mln": 6
    },
    "origin": "LOCAL",
    "time_fired": "2021-07-21T20:24:13.821741+00:00",
    "context": {
        "id": "9542c7f5b6673777770ea8608b44081b",
        "parent_id": null,
        "user_id": null
    }
}
Händelse 4 utlöst 22:24:
{
    "event_type": "mlgw.ML_telegram",
    "data": {
        "from_device": "VIDEO_MASTER",
        "to_device": "ALL_LINK_DEVICES",
        "type": "INFO",
        "src_dest": "NONE",
        "orig_src": "NONE",
        "payload_type": "START_VIDEO_DISTRIBUTION",
        "payload_len": 1,
        "payload": {},
        "timestamp": "2021-07-21T22:23:46.209000",
        "bytes": "83c0012c00000007010003",
        "from_mln": 6
    },
    "origin": "LOCAL",
    "time_fired": "2021-07-21T20:24:13.821340+00:00",
    "context": {
        "id": "d6179c046874bbdb0ba0b4e87f64b89f",
        "parent_id": null,
        "user_id": null
    }
}
Händelse 3 utlöst 22:23:
{
    "event_type": "mlgw.ML_telegram",
    "data": {
        "from_device": "VIDEO_MASTER",
        "to_device": "ALL_LINK_DEVICES",
        "type": "RESPONSE",
        "src_dest": "NONE",
        "orig_src": "NONE",
        "payload_type": "STATUS_INFO",
        "payload_len": 21,
        "payload": {
            "source": "TV",
            "sourceID": 11,
            "DTV_off": 0,
            "source_medium": "0xffff",
            "channel_track": 0,
            "activity": "Playing",
            "source_type": 2,
            "picture_identifier": "Not known"
        },
        "timestamp": "2021-07-21T22:23:14.810000",
        "bytes": "83c001140000008715040b090000008001ffff00ff02020000010000000000",
        "from_mln": 6
    },
    "origin": "LOCAL",
    "time_fired": "2021-07-21T20:23:42.253949+00:00",
    "context": {
        "id": "1cc7e88c295c6145093f2881308bd300",
        "parent_id": null,
        "user_id": null
    }
}
Händelse 2 utlöst 22:23:
{
    "event_type": "mlgw.ML_telegram",
    "data": {
        "from_device": "VIDEO_MASTER",
        "to_device": "ALL_LINK_DEVICES",
        "type": "RESPONSE",
        "src_dest": "NONE",
        "orig_src": "NONE",
        "payload_type": "VIDEO_TRACK_INFO",
        "payload_len": 7,
        "payload": {
            "source": "DTV",
            "sourceID": 31,
            "channel_track": "0xffff",
            "activity": "Playing"
        },
        "timestamp": "2021-07-21T22:23:06.079000",
        "bytes": "83c0011400000094070202ffff1f020094",
        "from_mln": 6
    },
    "origin": "LOCAL",
    "time_fired": "2021-07-21T20:23:33.735347+00:00",
    "context": {
        "id": "e95daa73fb7c984d9e52259038cb040f",
        "parent_id": null,
        "user_id": null
    }
}
Händelse 1 utlöst 22:23:
{
    "event_type": "mlgw.ML_telegram",
    "data": {
        "from_device": "VIDEO_MASTER",
        "to_device": "ALL_LINK_DEVICES",
        "type": "INFO",
        "src_dest": "NONE",
        "orig_src": "NONE",
        "payload_type": "START_VIDEO_DISTRIBUTION",
        "payload_len": 1,
        "payload": {},
        "timestamp": "2021-07-21T22:23:06.049000",
        "bytes": "83c0012c00000007010003",
        "from_mln": 6
    },
    "origin": "LOCAL",
    "time_fired": "2021-07-21T20:23:33.231834+00:00",
    "context": {
        "id": "b2352ba28dff413c0a67dbd4d52bdbc3",
        "parent_id": null,
        "user_id": null
    }
}
Händelse 0 utlöst 22:23:
{
    "event_type": "mlgw.ML_telegram",
    "data": {
        "from_device": "VIDEO_MASTER",
        "to_device": "ALL_LINK_DEVICES",
        "type": "RESPONSE",
        "src_dest": "NONE",
        "orig_src": "NONE",
        "payload_type": "STATUS_INFO",
        "payload_len": 21,
        "payload": {
            "source": "TV",
            "sourceID": 11,
            "DTV_off": 0,
            "source_medium": "0xffff",
            "channel_track": 0,
            "activity": "Playing",
            "source_type": 2,
            "picture_identifier": "Not known"
        },
        "timestamp": "2021-07-21T22:23:06.030000",
        "bytes": "83c001140000008715040b010000000001ffff00ff02020000010000000000",
        "from_mln": 6
    },
    "origin": "LOCAL",
    "time_fired": "2021-07-21T20:23:33.231695+00:00",
    "context": {
        "id": "6c42d11a72e0d4b43f86daf115b76880",
        "parent_id": null,
        "user_id": null
    }

**Comment by giachello** [comment]
Hi so it looks like these events are sent! 

you can use one of these events in your automation. Just create an automation that triggers on an "Event" and put in the matching fields E.g. "source" is "TV" and "activity" is "Playing". Check the examples in the code rep for guidance.

Giovanni

**Comment by oskarax** [comment]
Thanks! 

But it doesn't work. Under developer options when I look at the media player entity it switches between source: CD, RADIO but when I choose TV the state doesn't change so I can't create the automations I would like to.

**Comment by giachello** [comment]
You don't need to track the media player entity to start automations, you can also simply listen to the messages from mlgw, there are a few examples in the documentation.

Btw did you add TV to the sources configuration in the mlgw?
