### ISSUE TITLE
mlgw integration stops responding 

### ISSUE THREAD

**Issue by oskarax** [giachello/mlgw#9]
Hi! Seems that I'm the only one with issues..

I think this is related to after updating Home Assistant. The mlgw integration stops responding for no obvious reason a couple of times every day. Quick fix is to reboot Home Assistant then it starts working again. One thing that I'm noticing is that under the integration tab in Home Assistant I have around twenty MLGW Configure tabs, but its is already configured. 

Would appreciate a fix if possible. Please tell me what data you need for debug.

**Comment by oskarax** [comment]
Tried uninstalling but it doesn't fix the issue. It works a couple of hours then I have to reboot Home Assistant

**Comment by giachello** [comment]
So I did fix the bug of  the multiple configure tabs and that code is checked in 2021.8.1. However, it's hard to debug the other issue without further information. can you send me the debug logs?
(custom_components.mlgw: debug in configuration.yaml and then look into home-assistant.log)
thanks

**Comment by giachello** [comment]
I discovered a case in which when the MLGW reboots, the connection from the integration to the MLGW is broken (Socket Connection Reset). Will implement a recovery process to re open the connection when that happens.

**Comment by giachello** [comment]
I assume this is fixed after the latest bug fix in 2012.12.1 . Please re-open if you still have the issue.
